# Generated by Django 6.1 on 2026-08-12 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Overall grammar/clarity score, 0-100.', null=True)),
                ('summary', models.TextField(blank=True)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reviews', to='content.content')),
                ('content_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_reviews', to='versions.contentversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
