# Generated by Django 6.1 on 2026-08-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('version_restore', 'Version Restore'), ('submit_for_review', 'Submit For Review'), ('ai_review', 'AI Review'), ('approve', 'Approve'), ('reject', 'Reject'), ('publish', 'Publish')], max_length=30),
        ),
    ]
