# Generated by Django 6.1 on 2026-08-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('version_restore', 'Version Restore'), ('submit_for_review', 'Submit For Review'), ('ai_review', 'AI Review'), ('assign_reviewer', 'Assign Reviewer'), ('approve', 'Approve'), ('reject', 'Reject'), ('publish', 'Publish'), ('schedule_publish', 'Schedule Publish')], max_length=30),
        ),
    ]
