# Generated by Django 6.1 on 2026-08-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='published_at',
        ),
        migrations.AddField(
            model_name='content',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='If set, this content will be auto-published at this time.', null=True),
        ),
    ]
