# Generated by Django 6.1 on 2026-08-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_content_published_at_content_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
