# Generated by Django 6.1 on 2026-08-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.CharField(blank=True, choices=[('tech', 'Tech'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('health', 'Health'), ('general', 'General')], default='general', help_text='Best-effort, set automatically by AI category detection.', max_length=20),
        ),
    ]
